apiVersion: v1
kind: Service
metadata:
  name: dotnetapp-service
spec:
  selector:
    app: dotnetapp
  ports:
  - protocol: TCP
    port: 8085
    targetPort: 8080
    nodePort: 30002
  type: NodePort
